(function () {
  var B = "/Redsea-monitor/";
  var items = [
    ["redsea/", "Rudé moře"],
    ["usa/", "USA"],
    ["europe/", "Evropa"],
    ["middle-east/", "Blízký východ"],
    ["asia/", "Čína a Asie"],
    ["japan/", "Japonsko"],
    ["czechia/", "Česko"],
    ["hledani/", "Hledání"],
    ["uspesnost/", "Úspěšnost"],
    ["navstevnost/", "Návštěvnost"]
  ];
  var path = location.pathname.replace(/index\.html$/, "");
  var linkCss = "flex:none;color:var(--brass,#b8863b);text-decoration:none;" +
    "border:1px solid var(--rule,rgba(184,134,59,.35));padding:4px 10px;border-radius:2px";
  var html = '<a href="' + B + '" style="' + linkCss + ';font-weight:600' +
    (path === B ? ";background:rgba(184,134,59,.18)" : "") + '">☰ Přehled</a>';
  items.forEach(function (it) {
    var href = B + it[0];
    var on = path === href;
    html += '<a href="' + href + '" style="' + linkCss +
      (on ? ";background:rgba(184,134,59,.18);font-weight:600" : "") + '">' + it[1] + "</a>";
  });
  var bar = document.createElement("nav");
  bar.setAttribute("aria-label", "Monitory");
  bar.style.cssText =
    "display:flex;gap:6px;overflow-x:auto;white-space:nowrap;padding:8px 12px;" +
    "background:var(--ink2,#142c3a);border-bottom:1px solid var(--rule,rgba(184,134,59,.35));" +
    "font-family:'IBM Plex Mono',monospace;font-size:12px;letter-spacing:.03em";
  bar.innerHTML = html;
  document.body.insertBefore(bar, document.body.firstChild);

  // Upozornění u investičních doporučení (nejen pro monitory, kde je sekce "sec-recs")
  try {
    var h = document.getElementById("sec-recs");
    if (!h) {
      var hs = document.querySelectorAll("h2");
      for (var i = 0; i < hs.length; i++) {
        if (/investi/i.test(hs[i].textContent)) { h = hs[i]; break; }
      }
    }
    if (h && !document.getElementById("invest-disclaimer")) {
      var d = document.createElement("div");
      d.id = "invest-disclaimer";
      d.setAttribute("role", "note");
      d.style.cssText =
        "border:1px solid var(--rule,rgba(184,134,59,.35));border-left:3px solid var(--brass,#b8863b);" +
        "background:var(--ink2,#142c3a);padding:10px 12px;margin:0 0 14px;font-size:.82em;" +
        "line-height:1.55;color:var(--text-dim,#9aa8ac);font-family:'Spectral',Georgia,serif;" +
        "font-weight:400;letter-spacing:0;text-transform:none";
      d.innerHTML =
        "<b>Upozornění:</b> Níže uvedené signály vygenerovala umělá inteligence z veřejně dostupných zpráv. " +
        "Nejde o investiční doporučení, investiční poradenství ani nabídku k obchodování. " +
        "Mohou být nepřesné nebo zastaralé a minulá výkonnost nezaručuje budoucí výsledky. " +
        "Investice nese riziko ztráty. Rozhoduj se na základě vlastního posouzení nebo po konzultaci s licencovaným poradcem." +
        "<br><i>Disclaimer: The signals below are generated by AI from public news. They are not investment advice, " +
        "a recommendation or an offer to trade. They may be inaccurate or outdated, and past performance does not " +
        "guarantee future results. Investing involves risk of loss. Do your own research or consult a licensed advisor.</i>";
      h.insertAdjacentElement("afterend", d);
    }
  } catch (e) {}

  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.register(B + "sw.js", { scope: B }).catch(function () {});
  }
})();
